[package]
name = "sqlite-vs-doublets"
version = "0.2.0"
edition = "2024"
license = "Unlicense"
description = "Compares SQLite and Doublets as storage for links and for objects"

[dependencies]
doublets = "0.5.0"
rusqlite = { version = "0.40.2", features = ["bundled", "fallible_uint"] }
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
